// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvYH8Zqs16IXFjvki4_8gOYDB1ssy109o',
    appId: '1:1040566614538:web:d6cdb154ce303a84a2bdf3',
    messagingSenderId: '1040566614538',
    projectId: 'first-app-ced01',
    authDomain: 'first-app-ced01.firebaseapp.com',
    storageBucket: 'first-app-ced01.appspot.com',
    measurementId: 'G-0QZCXCQ0SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu3RcX1pvLAVPtqtlZMKTfm81tdX93CZk',
    appId: '1:1040566614538:android:b894e0fb69e7f16ba2bdf3',
    messagingSenderId: '1040566614538',
    projectId: 'first-app-ced01',
    storageBucket: 'first-app-ced01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAb_ov7RdoBRFHEk32pBnqxK_iXwFRQAM',
    appId: '1:1040566614538:ios:53db7236f3ceb953a2bdf3',
    messagingSenderId: '1040566614538',
    projectId: 'first-app-ced01',
    storageBucket: 'first-app-ced01.appspot.com',
    iosBundleId: 'com.example.se7etyy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAb_ov7RdoBRFHEk32pBnqxK_iXwFRQAM',
    appId: '1:1040566614538:ios:53db7236f3ceb953a2bdf3',
    messagingSenderId: '1040566614538',
    projectId: 'first-app-ced01',
    storageBucket: 'first-app-ced01.appspot.com',
    iosBundleId: 'com.example.se7etyy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvYH8Zqs16IXFjvki4_8gOYDB1ssy109o',
    appId: '1:1040566614538:web:95fe9518e350d990a2bdf3',
    messagingSenderId: '1040566614538',
    projectId: 'first-app-ced01',
    authDomain: 'first-app-ced01.firebaseapp.com',
    storageBucket: 'first-app-ced01.appspot.com',
    measurementId: 'G-KKVNMCHWTP',
  );

}